### PR TITLE
logos changes

### PR DESCRIPTION
**Pull request by OrneyVortex**

### CODE REVIEW

**Comment by RamGoel** [comment]
These logos has to be replaced by community partner logos, right?

**Comment by RamGoel** [comment]
Like GDSC JSS, GDSC ABESIT etc

**Comment by RamGoel** [comment]
You replaced with UN Sustsianbale goals

**Comment by OrneyVortex** [comment]
image

I talked to the content team they said ki upar yeh logos sahi lgenge and neeche joh ek section hum remove kr rhey they vaha yeh partner logos bdiya lgenge!!

**Pull request closed without merging**
